# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6323b0d330659e1101f0e7080839cedbaa22118c03bc2fffe8ca9f100c7ac3ecab466857d301e5c23e61e02bb8028a878fae50fd8844e2e06235403b2475d35

test:
  secret_key_base: 616de01da2b6f8090b4380643c3c6d4adbbee7233440ec187c280e135b652703740e6143a2c37592678260901496daa4b59ee1cd11b0d961d50468bcba975f80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
